let data = [
    {
        "id": "1",
        "name": "Belasco Llma Cognac",
        "img": "./img/Belasco-Llma-Cognac.png",
        "price": "33000",
        "star": "5",
        "wishlist": false,
        "inCart": 0,
    },
    {
        "id": "2",
        "name": "Camus Cognac Borderies XO",
        "img": "./img/Camus-Cognac-Borderies-XO.png",
        "price": "30000",
        "star": "5",
        "wishlist": true,
        "inCart": 1,
    },
    {
        "id": "3",
        "name": "Celasco Llma Cognac",
        "img": "./img/Celasco-Llma-Cognac.png",
        "price": "30000",
        "star": "5",
        "wishlist": true,
        "inCart": 0,
    },
    {
        "id": "4",
        "name": "Dry Vineyard Sauvignon",
        "img": "./img/Dry-Vineyard-Sauvignon.png",
        "price": "30000",
        "star": "5",
        "wishlist": false,
        "inCart": 1,
    },
    {
        "id": "5",
        "name": "Hennessy V.S Cognac",
        "img": "./img/Hennessy-V.S-Cognac.png",
        "price": "20000",
        "star": "3",
        "wishlist": true,
        "inCart": 2,
    },
    {
        "id": "6",
        "name": "Jack Daniel’s Old",
        "img": "./img/Jack-Daniel’s-Old.png",
        "price": "30000",
        "star": "4",
        "wishlist": false,
        "inCart": 3,
    },
    {
        "id": "7",
        "name": "Luctuson Chardonnavy",
        "img": "./img/Luctuson-Chardonnavy.png",
        "price": "33000",
        "star": "5",
        "wishlist": false,
        "inCart": 0,
    },
    {
        "id": "8",
        "name": "New Cabernet Sauvignon",
        "img": "./img/New-Cabernet-Sauvignon.png",
        "price": "33000",
        "star": "5",
        "wishlist": false,
        "inCart": 0,
    },
    {
        "id": "9",
        "name": "Rémy Martin VSOP",
        "img": "./img/Rémy-Martin-VSOP.png",
        "price": "33000",
        "star": "5",
        "wishlist": true,
        "inCart": 0,
    },
    {
        "id": "10",
        "name": "Hehelasco Llma Cognac",
        "img": "./img/Hehelasco-Llma-Cognac.png",
        "price": "30000",
        "star": "4",
        "wishlist": false,
        "inCart": 0,
    }
]
export default data;