export const GET_LIST_PRODUCTS = "GET_LIST_PRODUCTS";

export const GET_WISHLIST = "GET_WISHLIST";
export const DELETE_WISHLIST = "DELETE_WISHLIST";
export const ADD_WISHLIST = "ADD_WISHLIST";

export const GET_CARTLIST = "GET_CARTLIST";
export const CHANGE_NUMBER_ITEM_CART = "CHANGE_NUMBER_ITEM_CART";
export const DELETE_ITEM_CART = "DELETE_ITEM_CART";
export const ADD_ITEM_CART = "ADD_ITEM_CART";

export const ADD_COMPARE_PRODUCT = "ADD_COMPARE_PRODUCT";
export const DELETE_COMPARE_PRODUCT = "DELETE_COMPARE_PRODUCT";

export const ADD_PRODUCT_VIEW = "ADD_PRODUCT_VIEW";
